language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.2"
  - "2.3"
  - "4.0"
  - "5.0"
before_install:
  - npm install -g grunt-cli
  - npm install coffee-script
before_script: grunt build
script: npm run-script test-cov
after_success:
  - test -e ./coverage/lcov.info && npm install codeclimate-test-reporter && codeclimate-test-reporter
    < ./coverage/lcov.info
notifications:
  email:
    - snowyu.lee@gmail.com
addons:
  code_climate:
    repo_token:
      secure: "R7ii12vx43zyPkBjXUC6b4AZSu6Bd7MGkX9YN/SLHobFBxTnT8UNg+djyNi1wIkOyhJvXBHP6VlDMJYuZ/UsSHNnJ1z3zUoO7lAmUl0tvoxrYWvVB9Yc6N2ot0LFKUDyx0IJ4/JF98Nkv65BCBNKwpQU24W159jXNajTrGcrvzO2SA9JRXre5y1EcOd0dnEfVhMKn5VYwrO8VqOH6rYXXx+13Q8rNy+hleI/7/SZWxbQ+hP2o2xpYzwM8CAUSLmUMPDALStubaLl4cdmVad0bMeoWPxaKvzFiv8oqfCs/E3eVMK0GucVLCqCCHtO/5eeLBornvKqX8Gg5Er4+YBtAO1FAOtcsohq6M+DcQ36o6bZWK8fc2vGC8RlBWk6AAY1PnbW0luDnm75WU+k3BhlAlwOkjdpmTE337Mi2OO2634i9kaWDq4itasIG1SjUdjHGytvISSJ3TjWiIEvf0QfiI6Blf0YJ+TPLEb4wrlr12zDU6Ryfnclav7rSyDYPwnH1FZlxdJPYLlb9C3obi1Q4mTIh+XsnuvGMZTjzFdxvgC0mSE5J7UFRfE498wEgSr/m3RtFMTrdInpA4fMreJxgerpDihTWyQM8OzWwvLeZ8d8laY+96MULgQ6391hiDVXCkXp8/3qxsI9vNaLU3vbpB1eR3n2WIRDhCRQZwxJ+E4="
